apiVersion: v1
kind: Service
metadata:
  name: spark-app
  labels:
    app: spark-app
spec:
  ports:
  - port: 5006
    protocol: TCP
  clusterIP: None
  selector:
    app: spark-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-app
  labels:
    app: spark-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-app
  template:
    metadata:
      labels:
        app: spark-app
    spec:
      containers:
      - name: spark-app
        image: spark-app
 
      # Mount the volume that has been populated by the init container
      #     env:
      #       - name: HADOOP_CONF_DIR
      #         value: "/hadoop-config/"
      #       - name: HADOOP_USER_NAME
      #         value: "root"
      #       - name: HADOOP_JAAS_DEBUG
      #         value: "true"

      #     volumeMounts:
      #       - name: hadoop-conf-volume
      #         mountPath: /hadoop-config
      # volumes:
      #   - name: hadoop-conf-volume
      #     configMap:
      #       name: popular-slides-spark-hadoop-conf