apiVersion: v1
kind: Service
metadata:
  name: hadoop
  labels:
    app: hadoop
spec:
  ports:
  - port: 5003
    protocol: TCP
  clusterIP: None
  selector:
    app: hadoop
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hadoop
  labels:
    app: hadoop
spec:
  replicas: 3
  # muss mindestens 3 replicas haben, damit er eine pipeline bauen kann
  selector:
    matchLabels:
      app: hadoop
  template:
    metadata:
      labels:
        app: hadoop
    spec:
      containers:
      - name: hadoop
        image: hadoop
