apiVersion: v1
kind: Service
metadata:
  name: ozone
  labels:
    app: ozone
spec:
  ports:
  - port: 5005
    protocol: TCP
  clusterIP: None
  selector:
    app: ozone
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ozone
  labels:
    app: ozone
spec:
  replicas: 3
  # muss mindestens 3 replicas haben, damit er eine pipeline bauen kann
  selector:
    matchLabels:
      app: ozone
  template:
    metadata:
      labels:
        app: ozone
    spec:
      containers:
      - name: ozone
        image: ozone
