apiVersion: v1
kind: Service
metadata:
  name: docker-image-postgres
  labels:
    app: docker-image-postgres
spec:
  ports:
  - port: 5002
    protocol: TCP
  clusterIP: None
  selector:
    app: docker-image-postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-image-postgres
  labels:
    app: docker-image-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-image-postgres
  template:
    metadata:
      labels:
        app: docker-image-postgres
    spec:
      containers:
      - name: docker-image-postgres
        image: docker-image-postgres
