apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
 type: NodePort
 selector:
   app: my-app
   env: prod
 ports:
    #nodeport: 
 - nodePort: 32410
 #nodeport: Port auf dem dieser Service von außen erreichbar ist
   protocol: TCP
   
   

   
   port: 5002
      # port: Port den dieser Service exposed
   targetPort: 5000
   ## target Port: Port des Ziel-pods den dieser Service anspricht   
