#Begin Deplyment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: memcache-deployment
  labels:
    app: memcache-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memcached
  template:
    metadata:
      labels:
        app: memcached
    spec:
      containers:
        - name: memcached
          image: memcached:alpine
          ports:
            - containerPort: 11211
#End Deployment
---
#Begin Service
kind: Service
apiVersion: v1
metadata:
  name: memcached-service
spec:
  clusterIP: None
  selector:
    app: memcached
#End Service
