apiVersion: skaffold/v2beta21
kind: Config
metadata:
  name: skaffold-stable
# Erstellen der Artefakte
build:
  artifacts:
  - image: docker-image-postgres
    context: Docker_Image_Postgres
    docker:
      dockerfile: Dockerfile
  - image: flaskapp
    context: webapp
    docker:
      dockerfile: Dockerfile
  ## Wird aufgrund mangelnder Resourcen nicht gestartet
  # - image: sparkapp
  #   context: sparkapp
  #   docker:
  #     dockerfile: Dockerfile
  # - image: ozone
  #   context: ozone-docker
  #   docker:
  #     dockerfile: Dockerfile

  ## Nicht mehr verwendete/ nicht funktionierende Elemente
  # - image: python-kafka-publisher-demo
  #   context: python-publisher
  # - image: python-kafka-subscriber-demo
  #   context: python-subscriber
  # - image: dockertestapp
  #   context: dockertestapp
  #   docker:
  #     dockerfile: Dockerfile

# Deployen
deploy:
  kubectl:
    manifests:
     - cluster-def.yml
     - memchached_full.yaml
     - webapp/flask_app_deployment.yaml
     - Docker_Image_Postgres/deployment.yaml
     - webapp/flask-app-service.yaml
     ### Spark ist noch nicht auskonfiguriert, wird aus Performancegründen nicht 
     ### gestartet
     #  spark.yaml
     ### Portainer ist Optional zuschaltbar
     #- portainer/portainer.yml

## Nicht mehr verwendete/ nicht funktionierende Elemente
    #  - ./python-subscriber/k8s/*
    #  - ./python-publisher/k8s/*
    # - kafka/zookeeper_micro.yml
    # - kafka/kafka_micro.yaml
    # - nginx-service.yaml
    # - nginx.yaml
    # - strimzi-operator.yaml
    # - dockertestapp/deployment.yaml
    # - kafka/deployment.yaml
    # - role-binding.yml
    # - kafka-cluster-def.yaml
    # - service-account.yml
    # - kafka-service.yaml
    # - kafka-broker.yaml
    # - zookeeper.yml
    # - zooservice.yml
    # - hadoop/deployment.yaml
    # - k8s/popular-slides-app.yaml
    # - k8s/popular-slides-spark.yaml
    # - topic_creator.yml   ## wird nicht benötigt, topic wird automatisch erstellt
    # - ozone-docker/deployment.yaml
    # - spark-bitnami/deployment.yaml

  # Installation des Kafka-Helm-Charts
  helm:
    releases:
    - name: kafka-chart
      chartPath: ./strimzi-helm/
        
