apiVersion: skaffold/v2beta21
kind: Config
metadata:
  name: skaffold-test
build:
  artifacts:
  - image: docker-image-postgres
    context: Docker_Image_Postgres
    docker:
      dockerfile: Dockerfile
  - image: dockertestapp
    context: dockertestapp
    docker:
      dockerfile: Dockerfile
  - image: flaskapp
    context: webapp
    docker:
      dockerfile: Dockerfile
  # - image: hadoop
  #   context: hadoop
  #   docker:
  #     dockerfile: Dockerfile
  # - image: spark-bitnami
  #   context: spark-bitnami
  # - image: ozone
  #   context: ozone-docker
  #   docker:
  #     dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - memchached_full.yaml
    - portainer/portainer.yml
    - dockertestapp/deployment.yaml
    - Docker_Image_Postgres/deployment.yaml
    - webapp/flask-app-service.yaml
    - webapp/flask_app_deployment.yaml
    - portainer/portainer.yml
    # - nginx-service.yaml
    # - nginx.yaml

  # Folgende Pods starten bzw laufen noch nicht stabil

  # - hadoop/deployment.yaml
  # - ozone-docker/deployment.yaml'
  # - zookeeper.yml
  # - kafka-service.yaml
  # - zooservice.yml

  # Port Forwarding wird wohl nicht benötigt
# portForward:
  # - resourceType: service
    # resourceName: webserver
    # port: 8080
    # localPort: 9000
  # - resourceType: service
    # resourceName: nginx
    # port: 8080
    # localPort: 9001