apiVersion: skaffold/v2beta21
kind: Config
metadata:
  name: skaffold-stable
build:
  artifacts:
  - image: docker-image-postgres
    context: Docker_Image_Postgres
    docker:
      dockerfile: Dockerfile
  - image: dockertestapp
    context: dockertestapp
    docker:
      dockerfile: Dockerfile
  - image: flaskapp
    context: webapp
    docker:
      dockerfile: Dockerfile
  - image: ozone
    context: ozone-docker
    docker:
      dockerfile: Dockerfile
  # - image: kafka
  #   context: kafka
  #   docker:
  #     dockerfile: Dockerfile
  # - build:
  #   artifacts:
  #     - image: farberg/popular-slides
  #       context: web-app

  #     - image: farberg/popular-slides-spark
  #       context: spark-app
  # - image: spark-app
  #   context: spark-app
  #   docker:
  #     dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    # - kafka/zookeeper_micro.yml
    # - kafka/kafka_micro.yaml
     - memchached_full.yaml
    # - nginx-service.yaml
     - webapp/flask_app_deployment.yaml
     - Docker_Image_Postgres/deployment.yaml
    # - nginx.yaml
     - portainer/portainer.yml
    # - strimzi-operator.yaml
    # - dockertestapp/deployment.yaml
     - webapp/flask-app-service.yaml
    # - kafka/deployment.yaml
    # - role-binding.yml
    #  - kafka-cluster-def.yaml
     - test.yml
     - topic_creator.yml
    # - service-account.yml
    # - kafka-service.yaml
    # - kafka-broker.yaml
    # - zookeeper.yml
    # - zooservice.yml
    # - hadoop/deployment.yaml
    # - k8s/popular-slides-app.yaml
    # - k8s/popular-slides-spark.yaml
    # - ozone-docker/deployment.yaml
    # - spark-bitnami/deployment.yaml
  helm:
    releases:
    - name: kafka-chart
      chartPath: ./strimzi-helm/
        
