apiVersion: skaffold/v2beta21
kind: Config
metadata:
  name: skaffold-test
build:
  artifacts:
  - image: docker-image-postgres
    context: Docker_Image_Postgres
    docker:
      dockerfile: Dockerfile
  - image: dockertestapp
    context: dockertestapp
    docker:
      dockerfile: Dockerfile
  - image: flaskapp
    context: Docker_Image_App
    docker:
      dockerfile: Dockerfile
  - image: ngix
    context: ngix
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    #- kafka-service.yaml
    - memchached_full.yaml
    - Docker_Image_App/flask-app-service.yaml
    - mongo.yaml
    - zookeeper.yml
    - zooservice.yml
    - Docker_Image_App/flask_app_deployment.yaml
    - Docker_Image_Postgres/deployment.yaml
    - dockertestapp/deployment.yaml
    - ngix\deployment.yaml
portForward:
- resourceType: service
  resourceName: ngix
  port: 8080
  # das ist der Port des Pods/Services auf den weitergeleitet wird
  localPort: 9000
  # Das ist der Port der von der lokalen Maschine aus angesrpchen wird
- resourceType: service
  resourceName: flask-service
  port: 5001
  # das ist der Port des Pods/Services auf den weitergeleitet wird
  localPort: 9001
  # Das ist der Port der von der lokalen Maschine aus angesrpchen wird
