apiVersion: skaffold/v2beta21
kind: Config
metadata:
  name: skaffold-test
build:
  artifacts:
  - image: docker-image-postgres
    context: Docker_Image_Postgres
    docker:
      dockerfile: Dockerfile
  - image: dockertestapp
    context: dockertestapp
    docker:
      dockerfile: Dockerfile
  - image: flaskapp
    context: Docker_Image_App
    docker:
      dockerfile: Dockerfile
  - image: wurstmeister/kafka
    context: spark-app
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - kafka-service.yaml
    - memchached_full.yaml
    - mongo.yaml
    - zookeeper.yml
    - zooservice.yml
    - Docker_Image_App/flask-app-service.yaml
    - Docker_Image_App/flask_app_deployment.yaml
    - Docker_Image_Postgres/deployment.yaml
    - dockertestapp/deployment.yaml
